name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *' # Run daily, adjust the schedule as needed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "email@em.com"
        git config --global user.name "Sync [bot]"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/ValveSoftware/counter-strike.git  # Replace with the URL of the original repository

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main  # Replace 'main' with the branch you want to sync

    - name: Push changes to fork
      run: git push origin HEAD
